// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/kf/v2/pkg/kf/service-brokers/cluster/fake (interfaces: Client)

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	cluster "github.com/google/kf/v2/pkg/kf/service-brokers/cluster"
)

// FakeClient is a mock of Client interface.
type FakeClient struct {
	ctrl     *gomock.Controller
	recorder *FakeClientMockRecorder
}

// FakeClientMockRecorder is the mock recorder for FakeClient.
type FakeClientMockRecorder struct {
	mock *FakeClient
}

// NewFakeClient creates a new mock instance.
func NewFakeClient(ctrl *gomock.Controller) *FakeClient {
	mock := &FakeClient{ctrl: ctrl}
	mock.recorder = &FakeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FakeClient) EXPECT() *FakeClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *FakeClient) Create(arg0 context.Context, arg1 *v1alpha1.ClusterServiceBroker) (*v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *FakeClientMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*FakeClient)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *FakeClient) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *FakeClientMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*FakeClient)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *FakeClient) Get(arg0 context.Context, arg1 string) (*v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *FakeClientMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*FakeClient)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *FakeClient) List(arg0 context.Context) ([]v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *FakeClientMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*FakeClient)(nil).List), arg0)
}

// Transform mocks base method.
func (m *FakeClient) Transform(arg0 context.Context, arg1 string, arg2 cluster.Mutator) (*v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transform", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transform indicates an expected call of Transform.
func (mr *FakeClientMockRecorder) Transform(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transform", reflect.TypeOf((*FakeClient)(nil).Transform), arg0, arg1, arg2)
}

// Upsert mocks base method.
func (m *FakeClient) Upsert(arg0 context.Context, arg1 *v1alpha1.ClusterServiceBroker, arg2 cluster.Merger) (*v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *FakeClientMockRecorder) Upsert(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*FakeClient)(nil).Upsert), arg0, arg1, arg2)
}

// WaitFor mocks base method.
func (m *FakeClient) WaitFor(arg0 context.Context, arg1 string, arg2 time.Duration, arg3 cluster.Predicate) (*v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitFor", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitFor indicates an expected call of WaitFor.
func (mr *FakeClientMockRecorder) WaitFor(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitFor", reflect.TypeOf((*FakeClient)(nil).WaitFor), arg0, arg1, arg2, arg3)
}

// WaitForConditionReadyTrue mocks base method.
func (m *FakeClient) WaitForConditionReadyTrue(arg0 context.Context, arg1 string, arg2 time.Duration) (*v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForConditionReadyTrue", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForConditionReadyTrue indicates an expected call of WaitForConditionReadyTrue.
func (mr *FakeClientMockRecorder) WaitForConditionReadyTrue(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForConditionReadyTrue", reflect.TypeOf((*FakeClient)(nil).WaitForConditionReadyTrue), arg0, arg1, arg2)
}

// WaitForDeletion mocks base method.
func (m *FakeClient) WaitForDeletion(arg0 context.Context, arg1 string, arg2 time.Duration) (*v1alpha1.ClusterServiceBroker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForDeletion", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1alpha1.ClusterServiceBroker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForDeletion indicates an expected call of WaitForDeletion.
func (mr *FakeClientMockRecorder) WaitForDeletion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForDeletion", reflect.TypeOf((*FakeClient)(nil).WaitForDeletion), arg0, arg1, arg2)
}
