// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"
	fake "kf-operator/pkg/client/injection/informers/factory/fake"
	operand "kf-operator/pkg/client/injection/informers/operand/v1alpha1/operand"

	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = operand.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Operand().V1alpha1().Operands()
	return context.WithValue(ctx, operand.Key{}, inf), inf.Informer()
}
