// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kf-operator/pkg/apis/kfsystem/v1alpha1"
	kfsystemv1alpha1 "kf-operator/pkg/client/clientset/versioned/typed/kfsystem/v1alpha1"

	gentype "k8s.io/client-go/gentype"
)

// fakeKfSystems implements KfSystemInterface
type fakeKfSystems struct {
	*gentype.FakeClientWithList[*v1alpha1.KfSystem, *v1alpha1.KfSystemList]
	Fake *FakeKfV1alpha1
}

func newFakeKfSystems(fake *FakeKfV1alpha1) kfsystemv1alpha1.KfSystemInterface {
	return &fakeKfSystems{
		gentype.NewFakeClientWithList[*v1alpha1.KfSystem, *v1alpha1.KfSystemList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("kfsystems"),
			v1alpha1.SchemeGroupVersion.WithKind("KfSystem"),
			func() *v1alpha1.KfSystem { return &v1alpha1.KfSystem{} },
			func() *v1alpha1.KfSystemList { return &v1alpha1.KfSystemList{} },
			func(dst, src *v1alpha1.KfSystemList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.KfSystemList) []*v1alpha1.KfSystem { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.KfSystemList, items []*v1alpha1.KfSystem) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
