// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kfv1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceInstanceLister helps list ServiceInstances.
// All objects returned here must be treated as read-only.
type ServiceInstanceLister interface {
	// List lists all ServiceInstances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kfv1alpha1.ServiceInstance, err error)
	// ServiceInstances returns an object that can list and get ServiceInstances.
	ServiceInstances(namespace string) ServiceInstanceNamespaceLister
	ServiceInstanceListerExpansion
}

// serviceInstanceLister implements the ServiceInstanceLister interface.
type serviceInstanceLister struct {
	listers.ResourceIndexer[*kfv1alpha1.ServiceInstance]
}

// NewServiceInstanceLister returns a new ServiceInstanceLister.
func NewServiceInstanceLister(indexer cache.Indexer) ServiceInstanceLister {
	return &serviceInstanceLister{listers.New[*kfv1alpha1.ServiceInstance](indexer, kfv1alpha1.Resource("serviceinstance"))}
}

// ServiceInstances returns an object that can list and get ServiceInstances.
func (s *serviceInstanceLister) ServiceInstances(namespace string) ServiceInstanceNamespaceLister {
	return serviceInstanceNamespaceLister{listers.NewNamespaced[*kfv1alpha1.ServiceInstance](s.ResourceIndexer, namespace)}
}

// ServiceInstanceNamespaceLister helps list and get ServiceInstances.
// All objects returned here must be treated as read-only.
type ServiceInstanceNamespaceLister interface {
	// List lists all ServiceInstances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kfv1alpha1.ServiceInstance, err error)
	// Get retrieves the ServiceInstance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kfv1alpha1.ServiceInstance, error)
	ServiceInstanceNamespaceListerExpansion
}

// serviceInstanceNamespaceLister implements the ServiceInstanceNamespaceLister
// interface.
type serviceInstanceNamespaceLister struct {
	listers.ResourceIndexer[*kfv1alpha1.ServiceInstance]
}
