// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kfv1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceInstanceBindingLister helps list ServiceInstanceBindings.
// All objects returned here must be treated as read-only.
type ServiceInstanceBindingLister interface {
	// List lists all ServiceInstanceBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kfv1alpha1.ServiceInstanceBinding, err error)
	// ServiceInstanceBindings returns an object that can list and get ServiceInstanceBindings.
	ServiceInstanceBindings(namespace string) ServiceInstanceBindingNamespaceLister
	ServiceInstanceBindingListerExpansion
}

// serviceInstanceBindingLister implements the ServiceInstanceBindingLister interface.
type serviceInstanceBindingLister struct {
	listers.ResourceIndexer[*kfv1alpha1.ServiceInstanceBinding]
}

// NewServiceInstanceBindingLister returns a new ServiceInstanceBindingLister.
func NewServiceInstanceBindingLister(indexer cache.Indexer) ServiceInstanceBindingLister {
	return &serviceInstanceBindingLister{listers.New[*kfv1alpha1.ServiceInstanceBinding](indexer, kfv1alpha1.Resource("serviceinstancebinding"))}
}

// ServiceInstanceBindings returns an object that can list and get ServiceInstanceBindings.
func (s *serviceInstanceBindingLister) ServiceInstanceBindings(namespace string) ServiceInstanceBindingNamespaceLister {
	return serviceInstanceBindingNamespaceLister{listers.NewNamespaced[*kfv1alpha1.ServiceInstanceBinding](s.ResourceIndexer, namespace)}
}

// ServiceInstanceBindingNamespaceLister helps list and get ServiceInstanceBindings.
// All objects returned here must be treated as read-only.
type ServiceInstanceBindingNamespaceLister interface {
	// List lists all ServiceInstanceBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kfv1alpha1.ServiceInstanceBinding, err error)
	// Get retrieves the ServiceInstanceBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kfv1alpha1.ServiceInstanceBinding, error)
	ServiceInstanceBindingNamespaceListerExpansion
}

// serviceInstanceBindingNamespaceLister implements the ServiceInstanceBindingNamespaceLister
// interface.
type serviceInstanceBindingNamespaceLister struct {
	listers.ResourceIndexer[*kfv1alpha1.ServiceInstanceBinding]
}
