// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kfv1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TaskScheduleLister helps list TaskSchedules.
// All objects returned here must be treated as read-only.
type TaskScheduleLister interface {
	// List lists all TaskSchedules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kfv1alpha1.TaskSchedule, err error)
	// TaskSchedules returns an object that can list and get TaskSchedules.
	TaskSchedules(namespace string) TaskScheduleNamespaceLister
	TaskScheduleListerExpansion
}

// taskScheduleLister implements the TaskScheduleLister interface.
type taskScheduleLister struct {
	listers.ResourceIndexer[*kfv1alpha1.TaskSchedule]
}

// NewTaskScheduleLister returns a new TaskScheduleLister.
func NewTaskScheduleLister(indexer cache.Indexer) TaskScheduleLister {
	return &taskScheduleLister{listers.New[*kfv1alpha1.TaskSchedule](indexer, kfv1alpha1.Resource("taskschedule"))}
}

// TaskSchedules returns an object that can list and get TaskSchedules.
func (s *taskScheduleLister) TaskSchedules(namespace string) TaskScheduleNamespaceLister {
	return taskScheduleNamespaceLister{listers.NewNamespaced[*kfv1alpha1.TaskSchedule](s.ResourceIndexer, namespace)}
}

// TaskScheduleNamespaceLister helps list and get TaskSchedules.
// All objects returned here must be treated as read-only.
type TaskScheduleNamespaceLister interface {
	// List lists all TaskSchedules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kfv1alpha1.TaskSchedule, err error)
	// Get retrieves the TaskSchedule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kfv1alpha1.TaskSchedule, error)
	TaskScheduleNamespaceListerExpansion
}

// taskScheduleNamespaceLister implements the TaskScheduleNamespaceLister
// interface.
type taskScheduleNamespaceLister struct {
	listers.ResourceIndexer[*kfv1alpha1.TaskSchedule]
}
