// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/GoogleCloudPlatform/kf/pkg/apis/kf/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKfSpaces implements KfSpaceInterface
type FakeKfSpaces struct {
	Fake *FakeKfV1alpha1
}

var kfspacesResource = schema.GroupVersionResource{Group: "kf.dev", Version: "v1alpha1", Resource: "kfspaces"}

var kfspacesKind = schema.GroupVersionKind{Group: "kf.dev", Version: "v1alpha1", Kind: "KfSpace"}

// Get takes name of the kfSpace, and returns the corresponding kfSpace object, and an error if there is any.
func (c *FakeKfSpaces) Get(name string, options v1.GetOptions) (result *v1alpha1.KfSpace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kfspacesResource, name), &v1alpha1.KfSpace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KfSpace), err
}

// List takes label and field selectors, and returns the list of KfSpaces that match those selectors.
func (c *FakeKfSpaces) List(opts v1.ListOptions) (result *v1alpha1.KfSpaceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kfspacesResource, kfspacesKind, opts), &v1alpha1.KfSpaceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KfSpaceList{ListMeta: obj.(*v1alpha1.KfSpaceList).ListMeta}
	for _, item := range obj.(*v1alpha1.KfSpaceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kfSpaces.
func (c *FakeKfSpaces) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kfspacesResource, opts))
}

// Create takes the representation of a kfSpace and creates it.  Returns the server's representation of the kfSpace, and an error, if there is any.
func (c *FakeKfSpaces) Create(kfSpace *v1alpha1.KfSpace) (result *v1alpha1.KfSpace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kfspacesResource, kfSpace), &v1alpha1.KfSpace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KfSpace), err
}

// Update takes the representation of a kfSpace and updates it. Returns the server's representation of the kfSpace, and an error, if there is any.
func (c *FakeKfSpaces) Update(kfSpace *v1alpha1.KfSpace) (result *v1alpha1.KfSpace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kfspacesResource, kfSpace), &v1alpha1.KfSpace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KfSpace), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKfSpaces) UpdateStatus(kfSpace *v1alpha1.KfSpace) (*v1alpha1.KfSpace, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kfspacesResource, "status", kfSpace), &v1alpha1.KfSpace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KfSpace), err
}

// Delete takes name of the kfSpace and deletes it. Returns an error if one occurs.
func (c *FakeKfSpaces) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(kfspacesResource, name), &v1alpha1.KfSpace{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKfSpaces) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kfspacesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KfSpaceList{})
	return err
}

// Patch applies the patch and returns the patched kfSpace.
func (c *FakeKfSpaces) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KfSpace, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kfspacesResource, name, data, subresources...), &v1alpha1.KfSpace{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KfSpace), err
}
