steps:
  # the git steps are required to initialize a clean repo since
  # Cloud Build does not include the .git directory our scripts
  # use to orient themselves.
- name: gcr.io/cloud-builders/git
  args: ['init']
- name: gcr.io/cloud-builders/git
  args: ['add', '*']
- name: gcr.io/cloud-builders/git
  args: ['commit', '-m', "clean state", '--author', "Kf Builder <builder@kf.dev>"]
  # Run unit tests against the source
- name: golang:1.12
  entrypoint: /workspace/hack/ci.sh
  env:
  - SKIP_INTEGRATION=true
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - GOSUMDB=sum.golang.org
timeout: 600s
options:
  machineType: 'N1_HIGHCPU_8'
