steps:
- name: golang:1.12-buster
  entrypoint: /workspace/hack/ci.sh
  env:
  - SKIP_INTEGRATION=true
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - GOSUMDB=sum.golang.org
timeout: 600s
options:
  machineType: 'N1_HIGHCPU_8'
