// Code generated by injection-gen. DO NOT EDIT.

package clusteractiveoperand

import (
	context "context"
	v1alpha1 "kf-operator/pkg/client/informers/externalversions/operand/v1alpha1"
	factory "kf-operator/pkg/client/injection/informers/factory"

	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
	logging "knative.dev/pkg/logging"
)

func init() {
	injection.Default.RegisterInformer(withInformer)
}

// Key is used for associating the Informer inside the context.Context.
type Key struct{}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := factory.Get(ctx)
	inf := f.Operand().V1alpha1().ClusterActiveOperands()
	return context.WithValue(ctx, Key{}, inf), inf.Informer()
}

// Get extracts the typed informer from the context.
func Get(ctx context.Context) v1alpha1.ClusterActiveOperandInformer {
	untyped := ctx.Value(Key{})
	if untyped == nil {
		logging.FromContext(ctx).Panic(
			"Unable to fetch kf-operator/pkg/client/informers/externalversions/operand/v1alpha1.ClusterActiveOperandInformer from context.")
	}
	return untyped.(v1alpha1.ClusterActiveOperandInformer)
}
