# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
# # Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This can be ran by doing the following:
# gcloud builds submit . \
# --config=ci/cloudbuild/scheduled/reap-gke-clusters/cleanup-cron.yaml \
# --ignore-file=ci/cloudbuild/test.ignore \

timeout: 7200s
options:
  machineType: "N1_HIGHCPU_8"
steps:
  - id: reap infrastructure-manager deployments
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 3600s
    entrypoint: python3
    args: ["/scripts/delete_im_deployments.py", "${PROJECT_ID}"]

  - id: reap GKE clusters
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 3600s
    entrypoint: python3
    args: ["/scripts/delete_gke_clusters.py", "${PROJECT_ID}"]

  - id: reap load balancers
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 3600s
    entrypoint: python3
    args: ["/scripts/cleanup_load_balancers.py", "${PROJECT_ID}"]

  - id: reap firewall rules
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 3600s
    entrypoint: python3
    args: ["/scripts/cleanup_firewall_rules.py", "${PROJECT_ID}"]

  - id: reap disks
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 3600s
    entrypoint: python3
    args: ["/scripts/delete_disks.py", "${PROJECT_ID}"]

  - id: reap IAM policy bindings
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 3600s
    entrypoint: python3
    args: ["/scripts/reap_iam_bindings.py", "${PROJECT_ID}"]

  - id: reap Hub memberships
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 3600s
    entrypoint: python3
    args: ["/scripts/reap_hub_memberships.py", "${PROJECT_ID}"]

  - id: reap container images
    name: "gcr.io/${PROJECT_ID}/reap-gke-clusters"
    timeout: 7200s # slow operation, allow up to 2h to complete
    entrypoint: python3
    args: ["/scripts/reap_gcr_containers.py", "${PROJECT_ID}"]
