// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/google/kf/pkg/apis/kf/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RouteClaimLister helps list RouteClaims.
type RouteClaimLister interface {
	// List lists all RouteClaims in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.RouteClaim, err error)
	// RouteClaims returns an object that can list and get RouteClaims.
	RouteClaims(namespace string) RouteClaimNamespaceLister
	RouteClaimListerExpansion
}

// routeClaimLister implements the RouteClaimLister interface.
type routeClaimLister struct {
	indexer cache.Indexer
}

// NewRouteClaimLister returns a new RouteClaimLister.
func NewRouteClaimLister(indexer cache.Indexer) RouteClaimLister {
	return &routeClaimLister{indexer: indexer}
}

// List lists all RouteClaims in the indexer.
func (s *routeClaimLister) List(selector labels.Selector) (ret []*v1alpha1.RouteClaim, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RouteClaim))
	})
	return ret, err
}

// RouteClaims returns an object that can list and get RouteClaims.
func (s *routeClaimLister) RouteClaims(namespace string) RouteClaimNamespaceLister {
	return routeClaimNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RouteClaimNamespaceLister helps list and get RouteClaims.
type RouteClaimNamespaceLister interface {
	// List lists all RouteClaims in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.RouteClaim, err error)
	// Get retrieves the RouteClaim from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.RouteClaim, error)
	RouteClaimNamespaceListerExpansion
}

// routeClaimNamespaceLister implements the RouteClaimNamespaceLister
// interface.
type routeClaimNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RouteClaims in the indexer for a given namespace.
func (s routeClaimNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RouteClaim, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RouteClaim))
	})
	return ret, err
}

// Get retrieves the RouteClaim from the indexer for a given namespace and name.
func (s routeClaimNamespaceLister) Get(name string) (*v1alpha1.RouteClaim, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("routeclaim"), name)
	}
	return obj.(*v1alpha1.RouteClaim), nil
}
