[[buildpacks]]
id = "io.buildpacks.samples.nodejs"
uri = "./nodejs-buildpack"
latest = true

[[buildpacks]]
id = "io.buildpacks.samples.go"
uri = "./go-buildpack"
latest = true

[[buildpacks]]
id = "io.buildpacks.samples.java"
uri = "./java-buildpack"
latest = true

[[groups]]
buildpacks = [ { id = "io.buildpacks.samples.nodejs", version = "latest" } ]

[[groups]]
buildpacks = [ { id = "io.buildpacks.samples.go", version = "latest" } ]

[[groups]]
buildpacks = [ { id = "io.buildpacks.samples.java", version = "latest" } ]

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "REPLACE_WITH_REGISTRY/run:latest"
build-image = "REPLACE_WITH_REGISTRY/build:latest"
