// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	networkingv1 "github.com/google/kf/v2/pkg/client/kube/clientset/versioned/typed/networking/v1"
	v1 "k8s.io/api/networking/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIngressClasses implements IngressClassInterface
type fakeIngressClasses struct {
	*gentype.FakeClientWithList[*v1.IngressClass, *v1.IngressClassList]
	Fake *FakeNetworkingV1
}

func newFakeIngressClasses(fake *FakeNetworkingV1) networkingv1.IngressClassInterface {
	return &fakeIngressClasses{
		gentype.NewFakeClientWithList[*v1.IngressClass, *v1.IngressClassList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("ingressclasses"),
			v1.SchemeGroupVersion.WithKind("IngressClass"),
			func() *v1.IngressClass { return &v1.IngressClass{} },
			func() *v1.IngressClassList { return &v1.IngressClassList{} },
			func(dst, src *v1.IngressClassList) { dst.ListMeta = src.ListMeta },
			func(list *v1.IngressClassList) []*v1.IngressClass { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.IngressClassList, items []*v1.IngressClass) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
