//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOperand) DeepCopyInto(out *ActiveOperand) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOperand.
func (in *ActiveOperand) DeepCopy() *ActiveOperand {
	if in == nil {
		return nil
	}
	out := new(ActiveOperand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveOperand) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOperandList) DeepCopyInto(out *ActiveOperandList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActiveOperand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOperandList.
func (in *ActiveOperandList) DeepCopy() *ActiveOperandList {
	if in == nil {
		return nil
	}
	out := new(ActiveOperandList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveOperandList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOperandSpec) DeepCopyInto(out *ActiveOperandSpec) {
	*out = *in
	if in.Live != nil {
		in, out := &in.Live, &out.Live
		*out = make([]LiveRef, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOperandSpec.
func (in *ActiveOperandSpec) DeepCopy() *ActiveOperandSpec {
	if in == nil {
		return nil
	}
	out := new(ActiveOperandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOperandStatus) DeepCopyInto(out *ActiveOperandStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOperandStatus.
func (in *ActiveOperandStatus) DeepCopy() *ActiveOperandStatus {
	if in == nil {
		return nil
	}
	out := new(ActiveOperandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterActiveOperand) DeepCopyInto(out *ClusterActiveOperand) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterActiveOperand.
func (in *ClusterActiveOperand) DeepCopy() *ClusterActiveOperand {
	if in == nil {
		return nil
	}
	out := new(ClusterActiveOperand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterActiveOperand) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterActiveOperandList) DeepCopyInto(out *ClusterActiveOperandList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterActiveOperand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterActiveOperandList.
func (in *ClusterActiveOperandList) DeepCopy() *ClusterActiveOperandList {
	if in == nil {
		return nil
	}
	out := new(ClusterActiveOperandList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterActiveOperandList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterActiveOperandSpec) DeepCopyInto(out *ClusterActiveOperandSpec) {
	*out = *in
	if in.Live != nil {
		in, out := &in.Live, &out.Live
		*out = make([]LiveRef, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterActiveOperandSpec.
func (in *ClusterActiveOperandSpec) DeepCopy() *ClusterActiveOperandSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterActiveOperandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterActiveOperandStatus) DeepCopyInto(out *ClusterActiveOperandStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	if in.Delegates != nil {
		in, out := &in.Delegates, &out.Delegates
		*out = make([]DelegateRef, len(*in))
		copy(*out, *in)
	}
	if in.ClusterLive != nil {
		in, out := &in.ClusterLive, &out.ClusterLive
		*out = make([]LiveRef, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterActiveOperandStatus.
func (in *ClusterActiveOperandStatus) DeepCopy() *ClusterActiveOperandStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterActiveOperandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DelegateRef) DeepCopyInto(out *DelegateRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelegateRef.
func (in *DelegateRef) DeepCopy() *DelegateRef {
	if in == nil {
		return nil
	}
	out := new(DelegateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveRef) DeepCopyInto(out *LiveRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveRef.
func (in *LiveRef) DeepCopy() *LiveRef {
	if in == nil {
		return nil
	}
	out := new(LiveRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operand) DeepCopyInto(out *Operand) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operand.
func (in *Operand) DeepCopy() *Operand {
	if in == nil {
		return nil
	}
	out := new(Operand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Operand) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandList) DeepCopyInto(out *OperandList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Operand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandList.
func (in *OperandList) DeepCopy() *OperandList {
	if in == nil {
		return nil
	}
	out := new(OperandList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperandList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandSpec) DeepCopyInto(out *OperandSpec) {
	*out = *in
	if in.SteadyState != nil {
		in, out := &in.SteadyState, &out.SteadyState
		*out = make([]unstructured.Unstructured, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostInstall != nil {
		in, out := &in.PostInstall, &out.PostInstall
		*out = make([]unstructured.Unstructured, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandSpec.
func (in *OperandSpec) DeepCopy() *OperandSpec {
	if in == nil {
		return nil
	}
	out := new(OperandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperandStatus) DeepCopyInto(out *OperandStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperandStatus.
func (in *OperandStatus) DeepCopy() *OperandStatus {
	if in == nil {
		return nil
	}
	out := new(OperandStatus)
	in.DeepCopyInto(out)
	return out
}
