// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kfv1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	scheme "github.com/google/kf/v2/pkg/client/kf/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterServiceBrokersGetter has a method to return a ClusterServiceBrokerInterface.
// A group's client should implement this interface.
type ClusterServiceBrokersGetter interface {
	ClusterServiceBrokers() ClusterServiceBrokerInterface
}

// ClusterServiceBrokerInterface has methods to work with ClusterServiceBroker resources.
type ClusterServiceBrokerInterface interface {
	Create(ctx context.Context, clusterServiceBroker *kfv1alpha1.ClusterServiceBroker, opts v1.CreateOptions) (*kfv1alpha1.ClusterServiceBroker, error)
	Update(ctx context.Context, clusterServiceBroker *kfv1alpha1.ClusterServiceBroker, opts v1.UpdateOptions) (*kfv1alpha1.ClusterServiceBroker, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterServiceBroker *kfv1alpha1.ClusterServiceBroker, opts v1.UpdateOptions) (*kfv1alpha1.ClusterServiceBroker, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kfv1alpha1.ClusterServiceBroker, error)
	List(ctx context.Context, opts v1.ListOptions) (*kfv1alpha1.ClusterServiceBrokerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kfv1alpha1.ClusterServiceBroker, err error)
	ClusterServiceBrokerExpansion
}

// clusterServiceBrokers implements ClusterServiceBrokerInterface
type clusterServiceBrokers struct {
	*gentype.ClientWithList[*kfv1alpha1.ClusterServiceBroker, *kfv1alpha1.ClusterServiceBrokerList]
}

// newClusterServiceBrokers returns a ClusterServiceBrokers
func newClusterServiceBrokers(c *KfV1alpha1Client) *clusterServiceBrokers {
	return &clusterServiceBrokers{
		gentype.NewClientWithList[*kfv1alpha1.ClusterServiceBroker, *kfv1alpha1.ClusterServiceBrokerList](
			"clusterservicebrokers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *kfv1alpha1.ClusterServiceBroker { return &kfv1alpha1.ClusterServiceBroker{} },
			func() *kfv1alpha1.ClusterServiceBrokerList { return &kfv1alpha1.ClusterServiceBrokerList{} },
		),
	}
}
