// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kfv1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	scheme "github.com/google/kf/v2/pkg/client/kf/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ScalesGetter has a method to return a ScaleInterface.
// A group's client should implement this interface.
type ScalesGetter interface {
	Scales(namespace string) ScaleInterface
}

// ScaleInterface has methods to work with Scale resources.
type ScaleInterface interface {
	Create(ctx context.Context, scale *kfv1alpha1.Scale, opts v1.CreateOptions) (*kfv1alpha1.Scale, error)
	Update(ctx context.Context, scale *kfv1alpha1.Scale, opts v1.UpdateOptions) (*kfv1alpha1.Scale, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kfv1alpha1.Scale, error)
	List(ctx context.Context, opts v1.ListOptions) (*kfv1alpha1.ScaleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kfv1alpha1.Scale, err error)
	ScaleExpansion
}

// scales implements ScaleInterface
type scales struct {
	*gentype.ClientWithList[*kfv1alpha1.Scale, *kfv1alpha1.ScaleList]
}

// newScales returns a Scales
func newScales(c *KfV1alpha1Client, namespace string) *scales {
	return &scales{
		gentype.NewClientWithList[*kfv1alpha1.Scale, *kfv1alpha1.ScaleList](
			"scales",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kfv1alpha1.Scale { return &kfv1alpha1.Scale{} },
			func() *kfv1alpha1.ScaleList { return &kfv1alpha1.ScaleList{} },
		),
	}
}
