// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kfv1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	scheme "github.com/google/kf/v2/pkg/client/kf/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceBrokersGetter has a method to return a ServiceBrokerInterface.
// A group's client should implement this interface.
type ServiceBrokersGetter interface {
	ServiceBrokers(namespace string) ServiceBrokerInterface
}

// ServiceBrokerInterface has methods to work with ServiceBroker resources.
type ServiceBrokerInterface interface {
	Create(ctx context.Context, serviceBroker *kfv1alpha1.ServiceBroker, opts v1.CreateOptions) (*kfv1alpha1.ServiceBroker, error)
	Update(ctx context.Context, serviceBroker *kfv1alpha1.ServiceBroker, opts v1.UpdateOptions) (*kfv1alpha1.ServiceBroker, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceBroker *kfv1alpha1.ServiceBroker, opts v1.UpdateOptions) (*kfv1alpha1.ServiceBroker, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kfv1alpha1.ServiceBroker, error)
	List(ctx context.Context, opts v1.ListOptions) (*kfv1alpha1.ServiceBrokerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kfv1alpha1.ServiceBroker, err error)
	ServiceBrokerExpansion
}

// serviceBrokers implements ServiceBrokerInterface
type serviceBrokers struct {
	*gentype.ClientWithList[*kfv1alpha1.ServiceBroker, *kfv1alpha1.ServiceBrokerList]
}

// newServiceBrokers returns a ServiceBrokers
func newServiceBrokers(c *KfV1alpha1Client, namespace string) *serviceBrokers {
	return &serviceBrokers{
		gentype.NewClientWithList[*kfv1alpha1.ServiceBroker, *kfv1alpha1.ServiceBrokerList](
			"servicebrokers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kfv1alpha1.ServiceBroker { return &kfv1alpha1.ServiceBroker{} },
			func() *kfv1alpha1.ServiceBrokerList { return &kfv1alpha1.ServiceBrokerList{} },
		),
	}
}
