# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    operator.knative.dev/mode: Reconcile
  name: webhook.kf.dev
  labels:
    kf.dev/release: VERSION_PLACEHOLDER
webhooks:
- admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: webhook
      namespace: kf
  failurePolicy: Fail
  sideEffects: None
  name: webhook.kf.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    operator.knative.dev/mode: Reconcile
  name: validation.webhook.kf.dev
  labels:
    kf.dev/release: VERSION_PLACEHOLDER
webhooks:
- admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: webhook
      namespace: kf
  failurePolicy: Fail
  sideEffects: None
  name: validation.webhook.kf.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    operator.knative.dev/mode: Reconcile
  name: config.webhook.kf.dev
  labels:
    kf.dev/release: VERSION_PLACEHOLDER
webhooks:
- admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: webhook
      namespace: kf
  failurePolicy: Fail
  sideEffects: None
  name: config.webhook.kf.dev
  namespaceSelector:
    matchExpressions:
    - key: kf.dev/release
      operator: Exists
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    operator.knative.dev/mode: EnsureExists
  name: webhook-certs
  namespace: kf
  labels:
    kf.dev/release: VERSION_PLACEHOLDER
# The data is populated at install time.
