// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/kf/v2/pkg/kf/marketplace/fake (interfaces: ClientInterface)

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	marketplace "github.com/google/kf/v2/pkg/kf/marketplace"
)

// FakeClientInterface is a mock of ClientInterface interface.
type FakeClientInterface struct {
	ctrl     *gomock.Controller
	recorder *FakeClientInterfaceMockRecorder
}

// FakeClientInterfaceMockRecorder is the mock recorder for FakeClientInterface.
type FakeClientInterfaceMockRecorder struct {
	mock *FakeClientInterface
}

// NewFakeClientInterface creates a new mock instance.
func NewFakeClientInterface(ctrl *gomock.Controller) *FakeClientInterface {
	mock := &FakeClientInterface{ctrl: ctrl}
	mock.recorder = &FakeClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FakeClientInterface) EXPECT() *FakeClientInterfaceMockRecorder {
	return m.recorder
}

// Marketplace mocks base method.
func (m *FakeClientInterface) Marketplace(arg0 context.Context, arg1 string) (*marketplace.KfMarketplace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marketplace", arg0, arg1)
	ret0, _ := ret[0].(*marketplace.KfMarketplace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marketplace indicates an expected call of Marketplace.
func (mr *FakeClientInterfaceMockRecorder) Marketplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marketplace", reflect.TypeOf((*FakeClientInterface)(nil).Marketplace), arg0, arg1)
}
