// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GoogleCloudPlatform/kf/pkg/kf/fake (interfaces: EnvironmentClient)

// Package fake is a generated GoMock package.
package fake

import (
	kf "github.com/GoogleCloudPlatform/kf/pkg/kf"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// FakeEnvironmentClient is a mock of EnvironmentClient interface
type FakeEnvironmentClient struct {
	ctrl     *gomock.Controller
	recorder *FakeEnvironmentClientMockRecorder
}

// FakeEnvironmentClientMockRecorder is the mock recorder for FakeEnvironmentClient
type FakeEnvironmentClientMockRecorder struct {
	mock *FakeEnvironmentClient
}

// NewFakeEnvironmentClient creates a new mock instance
func NewFakeEnvironmentClient(ctrl *gomock.Controller) *FakeEnvironmentClient {
	mock := &FakeEnvironmentClient{ctrl: ctrl}
	mock.recorder = &FakeEnvironmentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *FakeEnvironmentClient) EXPECT() *FakeEnvironmentClientMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *FakeEnvironmentClient) List(arg0 string, arg1 ...kf.ListEnvOption) (map[string]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *FakeEnvironmentClientMockRecorder) List(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*FakeEnvironmentClient)(nil).List), varargs...)
}

// Set mocks base method
func (m *FakeEnvironmentClient) Set(arg0 string, arg1 map[string]string, arg2 ...kf.SetEnvOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *FakeEnvironmentClientMockRecorder) Set(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*FakeEnvironmentClient)(nil).Set), varargs...)
}
