// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/kf/pkg/kf/fake (interfaces: LogTailer)

// Package fake is a generated GoMock package.
package fake

import (
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
)

// FakeLogTailer is a mock of LogTailer interface
type FakeLogTailer struct {
	ctrl     *gomock.Controller
	recorder *FakeLogTailerMockRecorder
}

// FakeLogTailerMockRecorder is the mock recorder for FakeLogTailer
type FakeLogTailerMockRecorder struct {
	mock *FakeLogTailer
}

// NewFakeLogTailer creates a new mock instance
func NewFakeLogTailer(ctrl *gomock.Controller) *FakeLogTailer {
	mock := &FakeLogTailer{ctrl: ctrl}
	mock.recorder = &FakeLogTailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *FakeLogTailer) EXPECT() *FakeLogTailerMockRecorder {
	return m.recorder
}

// DeployLogs mocks base method
func (m *FakeLogTailer) DeployLogs(arg0 io.Writer, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployLogs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployLogs indicates an expected call of DeployLogs
func (mr *FakeLogTailerMockRecorder) DeployLogs(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployLogs", reflect.TypeOf((*FakeLogTailer)(nil).DeployLogs), arg0, arg1, arg2, arg3)
}
