// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"
	fake "kf-operator/pkg/client/injection/informers/factory/fake"
	clusteractiveoperand "kf-operator/pkg/client/injection/informers/operand/v1alpha1/clusteractiveoperand"

	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = clusteractiveoperand.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Operand().V1alpha1().ClusterActiveOperands()
	return context.WithValue(ctx, clusteractiveoperand.Key{}, inf), inf.Informer()
}
