// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kfsystemv1alpha1 "kf-operator/pkg/apis/kfsystem/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KfSystemLister helps list KfSystems.
// All objects returned here must be treated as read-only.
type KfSystemLister interface {
	// List lists all KfSystems in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kfsystemv1alpha1.KfSystem, err error)
	// Get retrieves the KfSystem from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kfsystemv1alpha1.KfSystem, error)
	KfSystemListerExpansion
}

// kfSystemLister implements the KfSystemLister interface.
type kfSystemLister struct {
	listers.ResourceIndexer[*kfsystemv1alpha1.KfSystem]
}

// NewKfSystemLister returns a new KfSystemLister.
func NewKfSystemLister(indexer cache.Indexer) KfSystemLister {
	return &kfSystemLister{listers.New[*kfsystemv1alpha1.KfSystem](indexer, kfsystemv1alpha1.Resource("kfsystem"))}
}
