// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	kfv1alpha1 "github.com/google/kf/v2/pkg/client/kf/clientset/versioned/typed/kf/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScales implements ScaleInterface
type fakeScales struct {
	*gentype.FakeClientWithList[*v1alpha1.Scale, *v1alpha1.ScaleList]
	Fake *FakeKfV1alpha1
}

func newFakeScales(fake *FakeKfV1alpha1, namespace string) kfv1alpha1.ScaleInterface {
	return &fakeScales{
		gentype.NewFakeClientWithList[*v1alpha1.Scale, *v1alpha1.ScaleList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scales"),
			v1alpha1.SchemeGroupVersion.WithKind("Scale"),
			func() *v1alpha1.Scale { return &v1alpha1.Scale{} },
			func() *v1alpha1.ScaleList { return &v1alpha1.ScaleList{} },
			func(dst, src *v1alpha1.ScaleList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScaleList) []*v1alpha1.Scale { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ScaleList, items []*v1alpha1.Scale) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
