// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/google/kf/v2/pkg/apis/kf/v1alpha1"
	kfv1alpha1 "github.com/google/kf/v2/pkg/client/kf/clientset/versioned/typed/kf/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterServiceBrokers implements ClusterServiceBrokerInterface
type fakeClusterServiceBrokers struct {
	*gentype.FakeClientWithList[*v1alpha1.ClusterServiceBroker, *v1alpha1.ClusterServiceBrokerList]
	Fake *FakeKfV1alpha1
}

func newFakeClusterServiceBrokers(fake *FakeKfV1alpha1) kfv1alpha1.ClusterServiceBrokerInterface {
	return &fakeClusterServiceBrokers{
		gentype.NewFakeClientWithList[*v1alpha1.ClusterServiceBroker, *v1alpha1.ClusterServiceBrokerList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusterservicebrokers"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterServiceBroker"),
			func() *v1alpha1.ClusterServiceBroker { return &v1alpha1.ClusterServiceBroker{} },
			func() *v1alpha1.ClusterServiceBrokerList { return &v1alpha1.ClusterServiceBrokerList{} },
			func(dst, src *v1alpha1.ClusterServiceBrokerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterServiceBrokerList) []*v1alpha1.ClusterServiceBroker {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterServiceBrokerList, items []*v1alpha1.ClusterServiceBroker) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
