// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kf-operator/pkg/apis/operand/v1alpha1"
	operandv1alpha1 "kf-operator/pkg/client/clientset/versioned/typed/operand/v1alpha1"

	gentype "k8s.io/client-go/gentype"
)

// fakeActiveOperands implements ActiveOperandInterface
type fakeActiveOperands struct {
	*gentype.FakeClientWithList[*v1alpha1.ActiveOperand, *v1alpha1.ActiveOperandList]
	Fake *FakeOperandV1alpha1
}

func newFakeActiveOperands(fake *FakeOperandV1alpha1, namespace string) operandv1alpha1.ActiveOperandInterface {
	return &fakeActiveOperands{
		gentype.NewFakeClientWithList[*v1alpha1.ActiveOperand, *v1alpha1.ActiveOperandList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("activeoperands"),
			v1alpha1.SchemeGroupVersion.WithKind("ActiveOperand"),
			func() *v1alpha1.ActiveOperand { return &v1alpha1.ActiveOperand{} },
			func() *v1alpha1.ActiveOperandList { return &v1alpha1.ActiveOperandList{} },
			func(dst, src *v1alpha1.ActiveOperandList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ActiveOperandList) []*v1alpha1.ActiveOperand {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ActiveOperandList, items []*v1alpha1.ActiveOperand) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
