// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "kf-operator/pkg/apis/operand/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterActiveOperands implements ClusterActiveOperandInterface
type FakeClusterActiveOperands struct {
	Fake *FakeOperandV1alpha1
}

var clusteractiveoperandsResource = schema.GroupVersionResource{Group: "operand.run.cloud.google.com", Version: "v1alpha1", Resource: "clusteractiveoperands"}

var clusteractiveoperandsKind = schema.GroupVersionKind{Group: "operand.run.cloud.google.com", Version: "v1alpha1", Kind: "ClusterActiveOperand"}

// Get takes name of the clusterActiveOperand, and returns the corresponding clusterActiveOperand object, and an error if there is any.
func (c *FakeClusterActiveOperands) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusteractiveoperandsResource, name), &v1alpha1.ClusterActiveOperand{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterActiveOperand), err
}

// List takes label and field selectors, and returns the list of ClusterActiveOperands that match those selectors.
func (c *FakeClusterActiveOperands) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterActiveOperandList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusteractiveoperandsResource, clusteractiveoperandsKind, opts), &v1alpha1.ClusterActiveOperandList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterActiveOperandList{ListMeta: obj.(*v1alpha1.ClusterActiveOperandList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterActiveOperandList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterActiveOperands.
func (c *FakeClusterActiveOperands) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusteractiveoperandsResource, opts))
}

// Create takes the representation of a clusterActiveOperand and creates it.  Returns the server's representation of the clusterActiveOperand, and an error, if there is any.
func (c *FakeClusterActiveOperands) Create(ctx context.Context, clusterActiveOperand *v1alpha1.ClusterActiveOperand, opts v1.CreateOptions) (result *v1alpha1.ClusterActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusteractiveoperandsResource, clusterActiveOperand), &v1alpha1.ClusterActiveOperand{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterActiveOperand), err
}

// Update takes the representation of a clusterActiveOperand and updates it. Returns the server's representation of the clusterActiveOperand, and an error, if there is any.
func (c *FakeClusterActiveOperands) Update(ctx context.Context, clusterActiveOperand *v1alpha1.ClusterActiveOperand, opts v1.UpdateOptions) (result *v1alpha1.ClusterActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusteractiveoperandsResource, clusterActiveOperand), &v1alpha1.ClusterActiveOperand{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterActiveOperand), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterActiveOperands) UpdateStatus(ctx context.Context, clusterActiveOperand *v1alpha1.ClusterActiveOperand, opts v1.UpdateOptions) (*v1alpha1.ClusterActiveOperand, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusteractiveoperandsResource, "status", clusterActiveOperand), &v1alpha1.ClusterActiveOperand{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterActiveOperand), err
}

// Delete takes name of the clusterActiveOperand and deletes it. Returns an error if one occurs.
func (c *FakeClusterActiveOperands) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusteractiveoperandsResource, name), &v1alpha1.ClusterActiveOperand{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterActiveOperands) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusteractiveoperandsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterActiveOperandList{})
	return err
}

// Patch applies the patch and returns the patched clusterActiveOperand.
func (c *FakeClusterActiveOperands) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusteractiveoperandsResource, name, pt, data, subresources...), &v1alpha1.ClusterActiveOperand{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterActiveOperand), err
}
