// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "kf-operator/pkg/apis/operand/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeActiveOperands implements ActiveOperandInterface
type FakeActiveOperands struct {
	Fake *FakeOperandV1alpha1
	ns   string
}

var activeoperandsResource = schema.GroupVersionResource{Group: "operand.run.cloud.google.com", Version: "v1alpha1", Resource: "activeoperands"}

var activeoperandsKind = schema.GroupVersionKind{Group: "operand.run.cloud.google.com", Version: "v1alpha1", Kind: "ActiveOperand"}

// Get takes name of the activeOperand, and returns the corresponding activeOperand object, and an error if there is any.
func (c *FakeActiveOperands) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(activeoperandsResource, c.ns, name), &v1alpha1.ActiveOperand{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveOperand), err
}

// List takes label and field selectors, and returns the list of ActiveOperands that match those selectors.
func (c *FakeActiveOperands) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ActiveOperandList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(activeoperandsResource, activeoperandsKind, c.ns, opts), &v1alpha1.ActiveOperandList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ActiveOperandList{ListMeta: obj.(*v1alpha1.ActiveOperandList).ListMeta}
	for _, item := range obj.(*v1alpha1.ActiveOperandList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested activeOperands.
func (c *FakeActiveOperands) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(activeoperandsResource, c.ns, opts))

}

// Create takes the representation of a activeOperand and creates it.  Returns the server's representation of the activeOperand, and an error, if there is any.
func (c *FakeActiveOperands) Create(ctx context.Context, activeOperand *v1alpha1.ActiveOperand, opts v1.CreateOptions) (result *v1alpha1.ActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(activeoperandsResource, c.ns, activeOperand), &v1alpha1.ActiveOperand{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveOperand), err
}

// Update takes the representation of a activeOperand and updates it. Returns the server's representation of the activeOperand, and an error, if there is any.
func (c *FakeActiveOperands) Update(ctx context.Context, activeOperand *v1alpha1.ActiveOperand, opts v1.UpdateOptions) (result *v1alpha1.ActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(activeoperandsResource, c.ns, activeOperand), &v1alpha1.ActiveOperand{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveOperand), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeActiveOperands) UpdateStatus(ctx context.Context, activeOperand *v1alpha1.ActiveOperand, opts v1.UpdateOptions) (*v1alpha1.ActiveOperand, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(activeoperandsResource, "status", c.ns, activeOperand), &v1alpha1.ActiveOperand{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveOperand), err
}

// Delete takes name of the activeOperand and deletes it. Returns an error if one occurs.
func (c *FakeActiveOperands) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(activeoperandsResource, c.ns, name), &v1alpha1.ActiveOperand{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActiveOperands) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(activeoperandsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ActiveOperandList{})
	return err
}

// Patch applies the patch and returns the patched activeOperand.
func (c *FakeActiveOperands) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ActiveOperand, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(activeoperandsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ActiveOperand{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveOperand), err
}
