// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	operandv1alpha1 "kf-operator/pkg/apis/operand/v1alpha1"
	scheme "kf-operator/pkg/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ActiveOperandsGetter has a method to return a ActiveOperandInterface.
// A group's client should implement this interface.
type ActiveOperandsGetter interface {
	ActiveOperands(namespace string) ActiveOperandInterface
}

// ActiveOperandInterface has methods to work with ActiveOperand resources.
type ActiveOperandInterface interface {
	Create(ctx context.Context, activeOperand *operandv1alpha1.ActiveOperand, opts v1.CreateOptions) (*operandv1alpha1.ActiveOperand, error)
	Update(ctx context.Context, activeOperand *operandv1alpha1.ActiveOperand, opts v1.UpdateOptions) (*operandv1alpha1.ActiveOperand, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, activeOperand *operandv1alpha1.ActiveOperand, opts v1.UpdateOptions) (*operandv1alpha1.ActiveOperand, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operandv1alpha1.ActiveOperand, error)
	List(ctx context.Context, opts v1.ListOptions) (*operandv1alpha1.ActiveOperandList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operandv1alpha1.ActiveOperand, err error)
	ActiveOperandExpansion
}

// activeOperands implements ActiveOperandInterface
type activeOperands struct {
	*gentype.ClientWithList[*operandv1alpha1.ActiveOperand, *operandv1alpha1.ActiveOperandList]
}

// newActiveOperands returns a ActiveOperands
func newActiveOperands(c *OperandV1alpha1Client, namespace string) *activeOperands {
	return &activeOperands{
		gentype.NewClientWithList[*operandv1alpha1.ActiveOperand, *operandv1alpha1.ActiveOperandList](
			"activeoperands",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operandv1alpha1.ActiveOperand { return &operandv1alpha1.ActiveOperand{} },
			func() *operandv1alpha1.ActiveOperandList { return &operandv1alpha1.ActiveOperandList{} },
		),
	}
}
