// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kf-operator/pkg/apis/operand/v1alpha1"
	"kf-operator/pkg/client/clientset/versioned/scheme"

	rest "k8s.io/client-go/rest"
)

type OperandV1alpha1Interface interface {
	RESTClient() rest.Interface
	ActiveOperandsGetter
	ClusterActiveOperandsGetter
	OperandsGetter
}

// OperandV1alpha1Client is used to interact with features provided by the operand.run.cloud.google.com group.
type OperandV1alpha1Client struct {
	restClient rest.Interface
}

func (c *OperandV1alpha1Client) ActiveOperands(namespace string) ActiveOperandInterface {
	return newActiveOperands(c, namespace)
}

func (c *OperandV1alpha1Client) ClusterActiveOperands() ClusterActiveOperandInterface {
	return newClusterActiveOperands(c)
}

func (c *OperandV1alpha1Client) Operands() OperandInterface {
	return newOperands(c)
}

// NewForConfig creates a new OperandV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*OperandV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &OperandV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new OperandV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *OperandV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new OperandV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *OperandV1alpha1Client {
	return &OperandV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *OperandV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
