// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	operandv1alpha1 "kf-operator/pkg/apis/operand/v1alpha1"
	scheme "kf-operator/pkg/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OperandsGetter has a method to return a OperandInterface.
// A group's client should implement this interface.
type OperandsGetter interface {
	Operands() OperandInterface
}

// OperandInterface has methods to work with Operand resources.
type OperandInterface interface {
	Create(ctx context.Context, operand *operandv1alpha1.Operand, opts v1.CreateOptions) (*operandv1alpha1.Operand, error)
	Update(ctx context.Context, operand *operandv1alpha1.Operand, opts v1.UpdateOptions) (*operandv1alpha1.Operand, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, operand *operandv1alpha1.Operand, opts v1.UpdateOptions) (*operandv1alpha1.Operand, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operandv1alpha1.Operand, error)
	List(ctx context.Context, opts v1.ListOptions) (*operandv1alpha1.OperandList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operandv1alpha1.Operand, err error)
	OperandExpansion
}

// operands implements OperandInterface
type operands struct {
	*gentype.ClientWithList[*operandv1alpha1.Operand, *operandv1alpha1.OperandList]
}

// newOperands returns a Operands
func newOperands(c *OperandV1alpha1Client) *operands {
	return &operands{
		gentype.NewClientWithList[*operandv1alpha1.Operand, *operandv1alpha1.OperandList](
			"operands",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *operandv1alpha1.Operand { return &operandv1alpha1.Operand{} },
			func() *operandv1alpha1.OperandList { return &operandv1alpha1.OperandList{} },
		),
	}
}
