// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/google/kf/pkg/apis/kf/v1alpha1"
	scheme "github.com/google/kf/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RouteClaimsGetter has a method to return a RouteClaimInterface.
// A group's client should implement this interface.
type RouteClaimsGetter interface {
	RouteClaims(namespace string) RouteClaimInterface
}

// RouteClaimInterface has methods to work with RouteClaim resources.
type RouteClaimInterface interface {
	Create(*v1alpha1.RouteClaim) (*v1alpha1.RouteClaim, error)
	Update(*v1alpha1.RouteClaim) (*v1alpha1.RouteClaim, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RouteClaim, error)
	List(opts v1.ListOptions) (*v1alpha1.RouteClaimList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RouteClaim, err error)
	RouteClaimExpansion
}

// routeClaims implements RouteClaimInterface
type routeClaims struct {
	client rest.Interface
	ns     string
}

// newRouteClaims returns a RouteClaims
func newRouteClaims(c *KfV1alpha1Client, namespace string) *routeClaims {
	return &routeClaims{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the routeClaim, and returns the corresponding routeClaim object, and an error if there is any.
func (c *routeClaims) Get(name string, options v1.GetOptions) (result *v1alpha1.RouteClaim, err error) {
	result = &v1alpha1.RouteClaim{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("routeclaims").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RouteClaims that match those selectors.
func (c *routeClaims) List(opts v1.ListOptions) (result *v1alpha1.RouteClaimList, err error) {
	result = &v1alpha1.RouteClaimList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("routeclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested routeClaims.
func (c *routeClaims) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("routeclaims").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a routeClaim and creates it.  Returns the server's representation of the routeClaim, and an error, if there is any.
func (c *routeClaims) Create(routeClaim *v1alpha1.RouteClaim) (result *v1alpha1.RouteClaim, err error) {
	result = &v1alpha1.RouteClaim{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("routeclaims").
		Body(routeClaim).
		Do().
		Into(result)
	return
}

// Update takes the representation of a routeClaim and updates it. Returns the server's representation of the routeClaim, and an error, if there is any.
func (c *routeClaims) Update(routeClaim *v1alpha1.RouteClaim) (result *v1alpha1.RouteClaim, err error) {
	result = &v1alpha1.RouteClaim{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("routeclaims").
		Name(routeClaim.Name).
		Body(routeClaim).
		Do().
		Into(result)
	return
}

// Delete takes name of the routeClaim and deletes it. Returns an error if one occurs.
func (c *routeClaims) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("routeclaims").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *routeClaims) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("routeclaims").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched routeClaim.
func (c *routeClaims) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RouteClaim, err error) {
	result = &v1alpha1.RouteClaim{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("routeclaims").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
