# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Store these in your credential manager.
vars:

# ci config vars
- &ci_git_uri ((ci_git_uri))
- &ci_git_branch ((ci_git_branch))
- &ci_image_uri ((ci_image_uri))

# ---- end vars ----

resources:
- name: ci-image-src
  type: git
  source:
    branch: *ci_git_branch
    uri: *ci_git_uri
    paths:
    - ci/concourse/image
- name: ci-image-kf-source
  type: docker-image
  source:
    repository: gcr.io/kf-source/ci-image
    username: _json_key
    password: ((kf_source_service_account_json))
- name: ci-image-kf-int
  type: docker-image
  source:
    repository: gcr.io/kf-int/ci-image
    username: _json_key
    password: ((kf_int_service_account_json))

jobs:
# builds the ci image for later steps/other pipelines
- name: ci-image
  serial: true
  plan:
  - get: ci-image-src
    trigger: true
  - aggregate:
    - put: ci-image-kf-source
      params:
        build: ci-image-src/ci/concourse/image
    - put: ci-image-kf-int
      params:
        build: ci-image-src/ci/concourse/image
