---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: build-system-cnb

outputs:
- name: artifactory

caches:
- path: go-module-cache

run:
  path: build-system-cnb/ci/package.sh
