// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	context "context"
	externalversions "kf-operator/pkg/client/informers/externalversions"
	fake "kf-operator/pkg/client/injection/client/fake"
	factory "kf-operator/pkg/client/injection/informers/factory"

	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = factory.Get

func init() {
	injection.Fake.RegisterInformerFactory(withInformerFactory)
}

func withInformerFactory(ctx context.Context) context.Context {
	c := fake.Get(ctx)
	opts := make([]externalversions.SharedInformerOption, 0, 1)
	if injection.HasNamespaceScope(ctx) {
		opts = append(opts, externalversions.WithNamespace(injection.GetNamespaceScope(ctx)))
	}
	return context.WithValue(ctx, factory.Key{},
		externalversions.NewSharedInformerFactoryWithOptions(c, controller.GetResyncPeriod(ctx), opts...))
}
