region = "us-west1"
vpc_network_name = "sweeps-test-private"
uaa_db_instance_name = "uaa-test-instance-7"
uaa_image = "gcr.io/kf-source/uaa-dockerfile"
uaa_cert_common_name = "uaa.example.com"
uaa_cert_organization = "mattysweeps inc"
