// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ActiveOperandListerExpansion allows custom methods to be added to
// ActiveOperandLister.
type ActiveOperandListerExpansion interface{}

// ActiveOperandNamespaceListerExpansion allows custom methods to be added to
// ActiveOperandNamespaceLister.
type ActiveOperandNamespaceListerExpansion interface{}

// ClusterActiveOperandListerExpansion allows custom methods to be added to
// ClusterActiveOperandLister.
type ClusterActiveOperandListerExpansion interface{}

// OperandListerExpansion allows custom methods to be added to
// OperandLister.
type OperandListerExpansion interface{}
