// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AppListerExpansion allows custom methods to be added to
// AppLister.
type AppListerExpansion interface{}

// AppNamespaceListerExpansion allows custom methods to be added to
// AppNamespaceLister.
type AppNamespaceListerExpansion interface{}

// RouteListerExpansion allows custom methods to be added to
// RouteLister.
type RouteListerExpansion interface{}

// RouteNamespaceListerExpansion allows custom methods to be added to
// RouteNamespaceLister.
type RouteNamespaceListerExpansion interface{}

// SourceListerExpansion allows custom methods to be added to
// SourceLister.
type SourceListerExpansion interface{}

// SourceNamespaceListerExpansion allows custom methods to be added to
// SourceNamespaceLister.
type SourceNamespaceListerExpansion interface{}

// SpaceListerExpansion allows custom methods to be added to
// SpaceLister.
type SpaceListerExpansion interface{}
